bun/.devcontainer/Dockerfile
=> Using official Bun Docker image

.gitignore, react-browser/.codesandbox/tasks.json, react-browser/index.html, react-browser/package-lock.json, react-browser/package.json, react-browser/src/App.jsx, react-browser/src/index.jsx, react-browser/src/styles.css, react-browser/vite.config.js
Added package-lock.json to the .gitignore file.
=> feat: Add package-lock.json to .gitignore

node-http-server/package.json, node-http-server/yarn.lock
Update the versions of @types/node and nodemon in package.json
=> fix: update node http server

.scripts/restart-all-templates.ts
Add eu-2 to list of clusters to restart templates on. Also added a hibernation step at last to ensure all templates are hibernated and forks use snapshots from disk.
=> add eu-2 cluster for restart templates script

.codesandbox/tasks.json, .github/workflows/update-files.yaml, .scripts/generate-files.ts, templates.json
This will be used to power our discover page
=> feat: add template.json to root repo

.scripts/generate-files.ts, templates.json
Accessed a wrong field, now it should work!
=> fix: git data creation

.github/workflows/update-files.yaml
The script is looping because all files update all the time!
=> fix: stop looping the commit creation

.github/workflows/update-files.yaml
=> fix: filename

.gitignore, README.md, sandbox-migration/.codesandbox/tasks.json, sandbox-migration/package.json
Needs to be merged: - https://github.com/codesandbox/static-template/pull/2544
=> feat: Add Sandbox migration template

vue-vite/package.json, vue-vite/pnpm-lock.yaml
=> fix: update vite vue

.github/workflows/recreate-template-snapshot.yaml
Add env for csb api token for recreating template snapshots
=> add env for csb api token in recreate template snaps

sandbox-migration/package.json
Remove unused dependencies and update vite and vite-plugin-react versions
=> feat: Remove react-scripts, we are migrating to Vite automatically

bun/.codesandbox/tasks.json, deno-fresh/.codesandbox/tasks.json, docusaurus/.codesandbox/tasks.json, gatsby/.codesandbox/tasks.json, python-flask-server/.codesandbox/tasks.json, qwik-vite/.codesandbox/tasks.json
Adds more ports that we check during the status check of templates
=> chore: add more ports to check

.scripts/restart-all-templates.ts, .scripts/status-check.ts, node-express-server/.codesandbox/tasks.json
This also makes restarts faster by doing them by 5 in parallel
=> fix: checks for templates and restart command

gleam/.codesandbox/template.json, nest/.codesandbox/template.json, node-express-server/.codesandbox/template.json, rails/.codesandbox/template.json
Noticed a few misplaced or not so accurate tags
=> fix: adjust some tags

nextjs/package.json, nextjs/pnpm-lock.yaml
There are some peer dependency issues with eslint 9
=> fix(nextjs): downgrade eslint to 8

gleam/.devcontainer/devcontainer.json, gleam/manifest.toml
Lots of nice improvements, so worth bumping the template 🎉
=> bump Gleam version to 1.1.0

.scripts/generate-files.ts
Could use this to sort templates on the website
=> feat: add insertedAt for templates

node/package.json
Hi, thanks as always for CodeSandbox + ecosystem! 🔥
Quick PR to fix the `"main"` field in `package.json` and remove the obsolete fields pointing at incorrect locations.
cc @CompuIves
=> Fix main, remove obsolete fields

.github/workflows/create-commit-message.yaml, .scripts/generate-commit-message.ts, nextjs/README.md
Uses the SDK to verify if a template is working or not when generating PRs. Looks like it's properly working now!
=> chore: use new way for generating sandboxes on PR

.scripts/pitcher-manager.ts
=> add fc-us-3 manager
